package com.monday.companycontact.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTRACT_GROUP.
 */
public class ContractGroup {

    private Long id;
    private String groupName;

    public ContractGroup() {
    }

    public ContractGroup(Long id) {
        this.id = id;
    }

    public ContractGroup(Long id, String groupName) {
        this.id = id;
        this.groupName = groupName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
