package com.monday.companycontact.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXTRA_NUM.
 */
public class ExtraNum {

    private Long id;
    private String extraNumName;
    private String extraNum;
    private Long providerId;

    public ExtraNum() {
    }

    public ExtraNum(Long id) {
        this.id = id;
    }

    public ExtraNum(Long id, String extraNumName, String extraNum, Long providerId) {
        this.id = id;
        this.extraNumName = extraNumName;
        this.extraNum = extraNum;
        this.providerId = providerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExtraNumName() {
        return extraNumName;
    }

    public void setExtraNumName(String extraNumName) {
        this.extraNumName = extraNumName;
    }

    public String getExtraNum() {
        return extraNum;
    }

    public void setExtraNum(String extraNum) {
        this.extraNum = extraNum;
    }

    public Long getProviderId() {
        return providerId;
    }

    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

}
