package com.monday.companycontact.db;

import com.monday.companycontact.utils.PingYinUtil;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROVIDER.
 */
public class Provider implements Serializable{

    private Long id;
    private String providerNum;
    /** Not-null value. */
    private String providerName;
    private String providerContactName;
    private String providerPhone;
    private String address;
    private String companyPhone;
    private String email;
    private String image;
    private String logistics;
    private String remark;
    private int groupId;
    /** Not-null value. */
    private String pinyin;
    /** Not-null value. */
    private String pingyin2;

    public Provider() {
    }

    public Provider(Long id) {
        this.id = id;
    }

    public Provider(Long id, String providerNum, String providerName, String providerContactName, String providerPhone, String address, String companyPhone, String email, String image, String logistics, String remark, int groupId, String pinyin, String pingyin2) {
        this.id = id;
        this.providerNum = providerNum;
        this.providerName = providerName;
        this.providerContactName = providerContactName;
        this.providerPhone = providerPhone;
        this.address = address;
        this.companyPhone = companyPhone;
        this.email = email;
        this.image = image;
        this.logistics = logistics;
        this.remark = remark;
        this.groupId = groupId;
        this.pinyin = pinyin;
        this.pingyin2 = pingyin2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProviderNum() {
        return providerNum;
    }

    public void setProviderNum(String providerNum) {
        this.providerNum = providerNum;
    }

    /** Not-null value. */
    public String getProviderName() {
        return providerName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public String getProviderContactName() {
        return providerContactName;
    }

    public void setProviderContactName(String providerContactName) {
        this.providerContactName = providerContactName;
    }

    public String getProviderPhone() {
        return providerPhone;
    }

    public void setProviderPhone(String providerPhone) {
        this.providerPhone = providerPhone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCompanyPhone() {
        return companyPhone;
    }

    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getLogistics() {
        return logistics;
    }

    public void setLogistics(String logistics) {
        this.logistics = logistics;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public int getGroupId() {
        return groupId;
    }

    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    /** Not-null value. */
    public String getPinyin() {
    	if(pinyin == null){
    		pinyin = PingYinUtil.getPingYin(getProviderName());
    		pinyin = pinyin.toLowerCase();
    	}
    	if(pinyin == null || pinyin.isEmpty()){
    		return "#";
    	}
        return pinyin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /** Not-null value. */
    public String getPingyin2() {
    	if(pingyin2 == null){
    		pingyin2 = "";
    		String pn = getProviderName().trim();
    		final int count = pn.length();
    		for(int i = 0; i < count; i++){
    			pingyin2 += PingYinUtil.getPingYin(pn.charAt(i) + "").charAt(0);
    		}
    		pingyin2 = pingyin2.toLowerCase();
    	}    		
    	
    	
    	if(pingyin2 == null || pingyin2.isEmpty()){
    		return "#";
    	}
        return pingyin2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPingyin2(String pingyin2) {
        this.pingyin2 = pingyin2;
    }

}
